[package]
name = "fad-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "404AD filter-list compiler CLI."

[[bin]]
name = "fad-compile"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
fad-dnr = { workspace = true }
fad-filter = { workspace = true }
postcard = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
